import type {SanityDocumentLike} from 'sanity'
import {getCliClient} from 'sanity/cli'

// remove all non-alphanumeric, multiple dashes, leading/trailing dashes
function slugify(str: string) {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]/gi, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
}

const ELF_TYPE_DOCUMENTS = [
  {_type: 'elf', name: 'Alaric', role: 'toy-maker', availability: 'full-time'},
  {_type: 'elf', name: 'Borin', role: 'sleigh-engineer', availability: 'part-time'},
  {_type: 'elf', name: 'Caldor', role: 'reindeer-handler', availability: 'seasonal'},
  {_type: 'elf', name: 'Dorin', role: 'toy-maker', availability: 'part-time'},
  {_type: 'elf', name: 'Elric', role: 'sleigh-engineer', availability: 'full-time'},
  {_type: 'elf', name: 'Falin', role: 'reindeer-handler', availability: 'full-time'},
  {_type: 'elf', name: 'Gorin', role: 'toy-maker', availability: 'seasonal'},
  {_type: 'elf', name: 'Haldor', role: 'sleigh-engineer', availability: 'part-time'},
  {_type: 'elf', name: 'Ivor', role: 'reindeer-handler', availability: 'full-time'},
  {_type: 'elf', name: 'Jarin', role: 'toy-maker', availability: 'seasonal'},
  {_type: 'elf', name: 'Korin', role: 'sleigh-engineer', availability: 'full-time'},
  {_type: 'elf', name: 'Lorin', role: 'reindeer-handler', availability: 'part-time'},
  {_type: 'elf', name: 'Mordin', role: 'toy-maker', availability: 'full-time'},
  {_type: 'elf', name: 'Norin', role: 'sleigh-engineer', availability: 'seasonal'},
  {_type: 'elf', name: 'Orin', role: 'reindeer-handler', availability: 'full-time'},
  {_type: 'elf', name: 'Palin', role: 'toy-maker', availability: 'part-time'},
  {_type: 'elf', name: 'Quorin', role: 'sleigh-engineer', availability: 'full-time'},
  {_type: 'elf', name: 'Rorin', role: 'reindeer-handler', availability: 'seasonal'},
  {_type: 'elf', name: 'Sorin', role: 'toy-maker', availability: 'full-time'},
  {_type: 'elf', name: 'Talin', role: 'sleigh-engineer', availability: 'part-time'},
  {_type: 'elf', name: 'Urin', role: 'reindeer-handler', availability: 'full-time'},
  {_type: 'elf', name: 'Vorin', role: 'toy-maker', availability: 'seasonal'},
  {_type: 'elf', name: 'Waldor', role: 'sleigh-engineer', availability: 'full-time'},
  {_type: 'elf', name: 'Xorin', role: 'reindeer-handler', availability: 'part-time'},
  {_type: 'elf', name: 'Yorin', role: 'toy-maker', availability: 'full-time'},
  {_type: 'elf', name: 'Zorin', role: 'sleigh-engineer', availability: 'seasonal'},
  {_type: 'elf', name: 'Aldor', role: 'reindeer-handler', availability: 'full-time'},
  {_type: 'elf', name: 'Baldor', role: 'toy-maker', availability: 'part-time'},
  {_type: 'elf', name: 'Calin', role: 'sleigh-engineer', availability: 'full-time'},
  {_type: 'elf', name: 'Dorin II', role: 'reindeer-handler', availability: 'seasonal'},
  {_type: 'elf', name: 'Evor', role: 'toy-maker', availability: 'full-time'},
  {_type: 'elf', name: 'Farlin', role: 'sleigh-engineer', availability: 'part-time'},
  {_type: 'elf', name: 'Gorin II', role: 'reindeer-handler', availability: 'full-time'},
  {_type: 'elf', name: 'Halvor', role: 'toy-maker', availability: 'seasonal'},
  {_type: 'elf', name: 'Ivor II', role: 'sleigh-engineer', availability: 'full-time'},
  {_type: 'elf', name: 'Jaldor', role: 'reindeer-handler', availability: 'part-time'},
  {_type: 'elf', name: 'Korin II', role: 'toy-maker', availability: 'full-time'},
  {_type: 'elf', name: 'Lorlin', role: 'sleigh-engineer', availability: 'seasonal'},
  {_type: 'elf', name: 'Malin', role: 'reindeer-handler', availability: 'full-time'},
].map((e) => ({...e, _id: slugify(`elf-${e.name}`)}))

const CHILD_TYPE_DOCUMENTS = [
  {
    _type: 'child',
    name: 'Emily Johnson',
    age: 7,
    address: '123 Maple Street, Snowville',
    status: 'nice',
    wishList: ['doll', 'bicycle', 'lego set'],
  },
  {
    _type: 'child',
    name: 'Liam Smith',
    age: 5,
    address: '456 Pine Lane, Frostville',
    status: 'naughty',
    wishList: ['action figure', 'remote car', 'puzzle'],
  },
  {
    _type: 'child',
    name: 'Sophia Brown',
    age: 8,
    address: '789 Oak Avenue, Wintertown',
    status: 'nice',
    wishList: ['book', 'art set', 'stuffed animal'],
  },
  {
    _type: 'child',
    name: 'Noah Davis',
    age: 6,
    address: '101 Birch Road, Iceville',
    status: 'naughty',
    wishList: ['train set', 'building blocks', 'robot'],
  },
  {
    _type: 'child',
    name: 'Ava Miller',
    age: 4,
    address: '202 Elm Street, Coldtown',
    status: 'nice',
    wishList: ['princess dress', 'puzzle', 'teddy bear'],
  },
  {
    _type: 'child',
    name: 'Oliver Wilson',
    age: 9,
    address: '303 Cedar Drive, Snowland',
    status: 'naughty',
    wishList: ['drone', 'basketball', 'race car set'],
  },
  {
    _type: 'child',
    name: 'Isabella Taylor',
    age: 5,
    address: '404 Aspen Court, Freezetown',
    status: 'nice',
    wishList: ['unicorn toy', 'coloring book', 'jump rope'],
  },
  {
    _type: 'child',
    name: 'Elijah Anderson',
    age: 7,
    address: '505 Fir Circle, Northpole',
    status: 'naughty',
    wishList: ['lego set', 'superhero costume', 'soccer ball'],
  },
  {
    _type: 'child',
    name: 'Mia Thomas',
    age: 6,
    address: '606 Spruce Lane, Frostville',
    status: 'nice',
    wishList: ['ballet shoes', 'puzzle', 'stuffed animal'],
  },
  {
    _type: 'child',
    name: 'James Jackson',
    age: 8,
    address: '707 Redwood Road, Snowtown',
    status: 'naughty',
    wishList: ['bike', 'video game', 'action figure'],
  },
  {
    _type: 'child',
    name: 'Amelia White',
    age: 4,
    address: '808 Walnut Avenue, Iceville',
    status: 'nice',
    wishList: ['tea set', 'princess crown', 'stuffed dog'],
  },
  {
    _type: 'child',
    name: 'Lucas Harris',
    age: 9,
    address: '909 Maple Street, Wintertown',
    status: 'naughty',
    wishList: ['football', 'skateboard', 'drone'],
  },
  {
    _type: 'child',
    name: 'Harper Clark',
    age: 6,
    address: '1010 Pine Road, Snowville',
    status: 'nice',
    wishList: ['fairy wings', 'art supplies', 'stuffed unicorn'],
  },
  {
    _type: 'child',
    name: 'Mason Young',
    age: 7,
    address: '1111 Oak Circle, Freezetown',
    status: 'naughty',
    wishList: ['robot', 'building blocks', 'race car'],
  },
  {
    _type: 'child',
    name: 'Ella Hall',
    age: 5,
    address: '1212 Birch Lane, Frostville',
    status: 'nice',
    wishList: ['dollhouse', 'coloring set', 'stuffed bunny'],
  },
  {
    _type: 'child',
    name: 'Ethan Adams',
    age: 8,
    address: '1313 Cedar Avenue, Snowland',
    status: 'naughty',
    wishList: ['video game', 'drone', 'action figure'],
  },
  {
    _type: 'child',
    name: 'Charlotte Wright',
    age: 6,
    address: '1414 Spruce Street, Wintertown',
    status: 'nice',
    wishList: ['princess tiara', 'puzzle', 'ballet shoes'],
  },
  {
    _type: 'child',
    name: 'Henry Green',
    age: 9,
    address: '1515 Fir Road, Iceville',
    status: 'naughty',
    wishList: ['basketball', 'skateboard', 'video game'],
  },
  {
    _type: 'child',
    name: 'Abigail Baker',
    age: 4,
    address: '1616 Redwood Court, Snowville',
    status: 'nice',
    wishList: ['tea set', 'teddy bear', 'princess dress'],
  },
  {
    _type: 'child',
    name: 'Alexander Perez',
    age: 7,
    address: '1717 Walnut Avenue, Frostville',
    status: 'naughty',
    wishList: ['race car', 'robot', 'building blocks'],
  },
  {
    _type: 'child',
    name: 'Grace Scott',
    age: 5,
    address: '1818 Maple Lane, Freezetown',
    status: 'nice',
    wishList: ['doll', 'coloring book', 'stuffed animal'],
  },
  {
    _type: 'child',
    name: 'Jack Turner',
    age: 6,
    address: '1919 Pine Street, Snowtown',
    status: 'naughty',
    wishList: ['train set', 'superhero costume', 'puzzle'],
  },
  {
    _type: 'child',
    name: 'Scarlett King',
    age: 8,
    address: '2020 Oak Court, Iceville',
    status: 'nice',
    wishList: ['ballet dress', 'stuffed dog', 'art set'],
  },
  {
    _type: 'child',
    name: 'William Campbell',
    age: 9,
    address: '2121 Birch Drive, Wintertown',
    status: 'naughty',
    wishList: ['lego set', 'bike', 'remote car'],
  },
  {
    _type: 'child',
    name: 'Avery Rodriguez',
    age: 4,
    address: '2222 Cedar Avenue, Frostville',
    status: 'nice',
    wishList: ['princess crown', 'tea set', 'puzzle'],
  },
  {
    _type: 'child',
    name: 'Jacob Mitchell',
    age: 7,
    address: '2323 Spruce Road, Snowville',
    status: 'naughty',
    wishList: ['drone', 'robot', 'race car'],
  },
  {
    _type: 'child',
    name: 'Lily Martinez',
    age: 6,
    address: '2424 Fir Circle, Freezetown',
    status: 'nice',
    wishList: ['stuffed unicorn', 'fairy wings', 'coloring set'],
  },
].map((c) => ({...c, _id: slugify(`child-${c.name}`)}))

const EVENT_TYPE_DOCUMENTS = [
  {
    _type: 'event',
    eventName: 'Toy Assembly Workshop',
    description: 'Elves gather to assemble toys for children worldwide.',
    date: '2024-11-15T10:00:00Z',
    location: 'Main Workshop Hall',
    attendees: ['Elf 1', 'Elf 2', 'Elf 3'],
  },
  {
    _type: 'event',
    eventName: 'Gift Wrapping Contest',
    description: 'Friendly competition to wrap gifts the fastest.',
    date: '2024-12-01T14:00:00Z',
    location: 'Gift Wrapping Area',
    attendees: ['Elf 4', 'Elf 5', 'Elf 6'],
  },
  {
    _type: 'event',
    eventName: 'Reindeer Health Check',
    description: 'Regular health check for the reindeer before Christmas Eve.',
    date: '2024-11-20T09:00:00Z',
    location: 'Reindeer Barn',
    attendees: ['Elf 7', 'Elf 8', 'Reindeer Care Team'],
  },
  {
    _type: 'event',
    eventName: 'North Pole Pep Rally',
    description: 'A motivational event to boost elf morale before the big night.',
    date: '2024-12-23T17:00:00Z',
    location: 'Main Square',
    attendees: ['All Elves', 'Santa Claus'],
  },
  {
    _type: 'event',
    eventName: 'Cookie Baking Marathon',
    description: 'Non-stop cookie baking to fill Santa’s sleigh.',
    date: '2024-12-18T08:00:00Z',
    location: 'Kitchen',
    attendees: ['Elf 9', 'Elf 10', 'Elf 11'],
  },
  {
    _type: 'event',
    eventName: 'Reindeer Flight Practice',
    description: 'Practice runs for the reindeer team before the Christmas Eve flight.',
    date: '2024-12-21T15:00:00Z',
    location: 'Flight Training Grounds',
    attendees: ['Reindeer', 'Santa Claus', 'Elf 12'],
  },
  {
    _type: 'event',
    eventName: 'Inventory Check',
    description: 'Complete inventory of toys, tools, and materials.',
    date: '2024-11-10T09:00:00Z',
    location: 'Storage Area',
    attendees: ['Elf 13', 'Elf 14', 'Inventory Team'],
  },
  {
    _type: 'event',
    eventName: 'Toy Testing Day',
    description: 'Testing the toys for safety and fun factor.',
    date: '2024-11-25T10:00:00Z',
    location: 'Toy Testing Room',
    attendees: ['Elf 15', 'Elf 16', 'Toy Testing Committee'],
  },
  {
    _type: 'event',
    eventName: 'Christmas Eve Prep Meeting',
    description: 'Final meeting to discuss logistics for Christmas Eve.',
    date: '2024-12-22T12:00:00Z',
    location: 'Conference Room',
    attendees: ['Santa Claus', 'Head Elves', 'Logistics Team'],
  },
  {
    _type: 'event',
    eventName: "Santa's Suit Fitting",
    description: "Fitting Santa's suit to ensure it’s ready for the big day.",
    date: '2024-12-15T10:00:00Z',
    location: 'Tailor Shop',
    attendees: ['Santa Claus', 'Elf 17', 'Tailoring Team'],
  },
  {
    _type: 'event',
    eventName: 'Reindeer Nutrition Workshop',
    description: 'Workshop on reindeer nutrition for better performance.',
    date: '2024-11-05T11:00:00Z',
    location: 'Reindeer Barn',
    attendees: ['Elf 18', 'Elf 19', 'Reindeer Care Team'],
  },
  {
    _type: 'event',
    eventName: 'Elf Appreciation Day',
    description: 'A day to appreciate the hard work of all elves.',
    date: '2024-12-24T08:00:00Z',
    location: 'Main Workshop Hall',
    attendees: ['All Elves', 'Santa Claus'],
  },
  {
    _type: 'event',
    eventName: 'Sleigh Inspection',
    description: 'Inspecting Santa’s sleigh to ensure it’s in top condition.',
    date: '2024-12-14T13:00:00Z',
    location: 'Garage',
    attendees: ['Elf 20', 'Sleigh Maintenance Team'],
  },
  {
    _type: 'event',
    eventName: 'Wish List Review',
    description: 'Final review of children’s wish lists before toy delivery.',
    date: '2024-12-10T10:00:00Z',
    location: 'Wish List Processing Center',
    attendees: ['Elf 21', 'Wish List Team'],
  },
  {
    _type: 'event',
    eventName: 'Christmas Countdown Celebration',
    description: 'Countdown to Christmas with songs and celebrations.',
    date: '2024-12-24T23:00:00Z',
    location: 'Main Square',
    attendees: ['All Elves', 'Santa Claus', 'Mrs. Claus'],
  },
  {
    _type: 'event',
    eventName: 'Gift Delivery Briefing',
    description: 'Final briefing on the global gift delivery route.',
    date: '2024-12-23T18:00:00Z',
    location: 'Control Room',
    attendees: ['Santa Claus', 'Head Elves', 'Navigation Team'],
  },
  {
    _type: 'event',
    eventName: 'Sleigh Loading',
    description: 'Loading all gifts into Santa’s sleigh.',
    date: '2024-12-24T12:00:00Z',
    location: 'Loading Dock',
    attendees: ['Elf 22', 'Loading Team', 'Santa Claus'],
  },
  {
    _type: 'event',
    eventName: 'Workshop Cleanup',
    description: 'Cleaning up the workshop after Christmas.',
    date: '2024-12-26T09:00:00Z',
    location: 'Main Workshop Hall',
    attendees: ['Elf 23', 'Cleanup Crew'],
  },
  {
    _type: 'event',
    eventName: 'Post-Christmas Debrief',
    description: 'Debrief to discuss the successes and lessons learned.',
    date: '2024-12-30T11:00:00Z',
    location: 'Conference Room',
    attendees: ['Santa Claus', 'Head Elves', 'Support Staff'],
  },
  {
    _type: 'event',
    eventName: "New Year's Party",
    description: 'Celebrating the New Year with Santa and the elves.',
    date: '2024-12-31T20:00:00Z',
    location: 'Main Square',
    attendees: ['All Elves', 'Santa Claus', 'Mrs. Claus'],
  },
].map((e) => ({...e, _id: slugify(`event-${e.eventName}`)}))

const GIFT_TYPE_DOCUMENTS = [
  {
    _type: 'gift',
    wishListItems: ['Lego Set', 'Toy Car', 'Action Figure'],
    requestDate: '2024-11-10T12:00:00Z',
    approvalStatus: 'approved',
  },
  {
    _type: 'gift',
    wishListItems: ['Doll House', 'Bicycle', 'Puzzle'],
    requestDate: '2024-11-12T15:00:00Z',
    approvalStatus: 'pending',
  },
  {
    _type: 'gift',
    wishListItems: ['Board Game', 'Stuffed Animal', 'Building Blocks'],
    requestDate: '2024-11-15T08:30:00Z',
    approvalStatus: 'approved',
  },
  {
    _type: 'gift',
    wishListItems: ['Scooter', 'Play-Doh Set', 'Crayons'],
    requestDate: '2024-11-18T11:00:00Z',
    approvalStatus: 'denied',
  },
  {
    _type: 'gift',
    wishListItems: ['RC Car', 'Video Game', 'Basketball'],
    requestDate: '2024-11-20T10:00:00Z',
    approvalStatus: 'pending',
  },
  {
    _type: 'gift',
    wishListItems: ['Train Set', 'Soccer Ball', 'Art Supplies'],
    requestDate: '2024-11-22T14:30:00Z',
    approvalStatus: 'approved',
  },
  {
    _type: 'gift',
    wishListItems: ['Toy Truck', 'Sketchbook', 'Jigsaw Puzzle'],
    requestDate: '2024-11-25T09:00:00Z',
    approvalStatus: 'approved',
  },
  {
    _type: 'gift',
    wishListItems: ['Kitchen Playset', 'Bicycle Helmet', 'Science Kit'],
    requestDate: '2024-11-28T13:45:00Z',
    approvalStatus: 'pending',
  },
  {
    _type: 'gift',
    wishListItems: ['Puzzle', 'Action Figure', "Rubik's Cube"],
    requestDate: '2024-12-01T12:00:00Z',
    approvalStatus: 'denied',
  },
  {
    _type: 'gift',
    wishListItems: ['Remote Control Helicopter', 'LEGO Set', 'Toy Guitar'],
    requestDate: '2024-12-03T11:30:00Z',
    approvalStatus: 'approved',
  },
  {
    _type: 'gift',
    wishListItems: ['Art Set', 'Dinosaur Toy', 'Roller Skates'],
    requestDate: '2024-12-05T10:00:00Z',
    approvalStatus: 'pending',
  },
  {
    _type: 'gift',
    wishListItems: ['Superhero Costume', 'LEGO Space Shuttle', 'Chess Set'],
    requestDate: '2024-12-07T09:15:00Z',
    approvalStatus: 'approved',
  },
  {
    _type: 'gift',
    wishListItems: ['Electric Train Set', 'Basketball', 'Action Figures'],
    requestDate: '2024-12-08T16:00:00Z',
    approvalStatus: 'denied',
  },
  {
    _type: 'gift',
    wishListItems: ['Doll', 'Baking Set', 'Toy Drum'],
    requestDate: '2024-12-10T12:30:00Z',
    approvalStatus: 'pending',
  },
  {
    _type: 'gift',
    wishListItems: ['Puzzle', 'Remote Control Boat', 'Kite'],
    requestDate: '2024-12-12T10:45:00Z',
    approvalStatus: 'approved',
  },
  {
    _type: 'gift',
    wishListItems: ['Robot Kit', 'Interactive Book', 'Soccer Ball'],
    requestDate: '2024-12-14T14:00:00Z',
    approvalStatus: 'approved',
  },
  {
    _type: 'gift',
    wishListItems: ['Race Car Set', 'Stuffed Animal', 'Board Game'],
    requestDate: '2024-12-16T08:30:00Z',
    approvalStatus: 'pending',
  },
  {
    _type: 'gift',
    wishListItems: ['Play-Doh Set', 'Toy Soldier', 'Toy Tool Set'],
    requestDate: '2024-12-18T11:45:00Z',
    approvalStatus: 'approved',
  },
  {
    _type: 'gift',
    wishListItems: ['Magic Kit', 'Action Figure', 'Train Set'],
    requestDate: '2024-12-20T10:00:00Z',
    approvalStatus: 'approved',
  },
  {
    _type: 'gift',
    wishListItems: ['Bicycle', 'Skateboard', 'Toy Cash Register'],
    requestDate: '2024-12-22T15:00:00Z',
    approvalStatus: 'pending',
  },
].map((g) => ({
  ...g,
  _id: slugify(`gift-${g.wishListItems.join('-')}`),
  child: {
    _type: 'reference',
    _ref: CHILD_TYPE_DOCUMENTS[Math.floor(Math.random() * CHILD_TYPE_DOCUMENTS.length)]._id,
  },
}))

const PARENT_TYPE_DOCUMENTS = [
  {
    _type: 'parent',
    name: 'John Smith',
    email: 'john.smith@example.com',
    phone: '+1-555-1234',
    address: '123 Elm Street, Chicago, IL',
  },
  {
    _type: 'parent',
    name: 'Jane Doe',
    email: 'jane.doe@example.com',
    phone: '+1-555-5678',
    address: '456 Maple Avenue, New York, NY',
  },
  {
    _type: 'parent',
    name: 'Michael Johnson',
    email: 'michael.johnson@example.com',
    phone: '+1-555-9012',
    address: '789 Oak Boulevard, Los Angeles, CA',
  },
  {
    _type: 'parent',
    name: 'Sarah Williams',
    email: 'sarah.williams@example.com',
    phone: '+1-555-3456',
    address: '321 Pine Drive, Houston, TX',
  },
  {
    _type: 'parent',
    name: 'David Brown',
    email: 'david.brown@example.com',
    phone: '+1-555-7890',
    address: '987 Cedar Lane, Miami, FL',
  },
  {
    _type: 'parent',
    name: 'Emily Davis',
    email: 'emily.davis@example.com',
    phone: '+1-555-2345',
    address: '654 Birch Road, Seattle, WA',
  },
  {
    _type: 'parent',
    name: 'Robert Miller',
    email: 'robert.miller@example.com',
    phone: '+1-555-6789',
    address: '112 Cherry Court, Boston, MA',
  },
  {
    _type: 'parent',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@example.com',
    phone: '+1-555-5432',
    address: '223 Willow Street, Denver, CO',
  },
  {
    _type: 'parent',
    name: 'James Taylor',
    email: 'james.taylor@example.com',
    phone: '+1-555-8765',
    address: '334 Spruce Way, Atlanta, GA',
  },
  {
    _type: 'parent',
    name: 'Mary Thomas',
    email: 'mary.thomas@example.com',
    phone: '+1-555-4321',
    address: '445 Fir Drive, San Francisco, CA',
  },
  {
    _type: 'parent',
    name: 'Richard White',
    email: 'richard.white@example.com',
    phone: '+1-555-9876',
    address: '556 Oakwood Terrace, Austin, TX',
  },
  {
    _type: 'parent',
    name: 'Laura Martinez',
    email: 'laura.martinez@example.com',
    phone: '+1-555-5674',
    address: '667 Cedarview Lane, Phoenix, AZ',
  },
  {
    _type: 'parent',
    name: 'Charles Harris',
    email: 'charles.harris@example.com',
    phone: '+1-555-1239',
    address: '778 Palm Street, Orlando, FL',
  },
  {
    _type: 'parent',
    name: 'Patricia Lee',
    email: 'patricia.lee@example.com',
    phone: '+1-555-2341',
    address: '889 Oak Hill Drive, Las Vegas, NV',
  },
  {
    _type: 'parent',
    name: 'Mark Robinson',
    email: 'mark.robinson@example.com',
    phone: '+1-555-3458',
    address: '990 Maplewood Road, Nashville, TN',
  },
  {
    _type: 'parent',
    name: 'Jennifer Clark',
    email: 'jennifer.clark@example.com',
    phone: '+1-555-5673',
    address: '101 Cedarpark Court, Columbus, OH',
  },
  {
    _type: 'parent',
    name: 'Steven Lewis',
    email: 'steven.lewis@example.com',
    phone: '+1-555-7892',
    address: '202 Birchmount Drive, Charlotte, NC',
  },
  {
    _type: 'parent',
    name: 'Susan Walker',
    email: 'susan.walker@example.com',
    phone: '+1-555-8901',
    address: '303 Sprucetree Way, Portland, OR',
  },
  {
    _type: 'parent',
    name: 'Paul Hall',
    email: 'paul.hall@example.com',
    phone: '+1-555-3450',
    address: '404 Redwood Drive, Salt Lake City, UT',
  },
  {
    _type: 'parent',
    name: 'Michelle Young',
    email: 'michelle.young@example.com',
    phone: '+1-555-9870',
    address: '505 Willowbend Lane, Kansas City, MO',
  },
].map((p) => ({
  ...p,
  _id: slugify(`parent-${p.name}`),
  children: Array.from(
    {length: Math.floor(Math.random() * 3) + 1},
    () => CHILD_TYPE_DOCUMENTS[Math.floor(Math.random() * CHILD_TYPE_DOCUMENTS.length)]._id,
  ).map((childId) => ({_type: 'reference', _ref: childId, _key: childId})),
}))

const PEOPLE_TYPE_DOCUMENTS = [
  {
    _type: 'person',
    name: 'Mrs. Claus',
    email: 'mrs.claus@northpole.com',
    phone: '+1-555-1234',
    address: "Santa's Workshop, North Pole",
  },
  {
    _type: 'person',
    name: 'Head Toy Designer',
    email: 'designer@northpole.com',
    phone: '+1-555-5678',
    address: 'Toy Design Office, North Pole',
  },
  {
    _type: 'person',
    name: 'Workshop Manager',
    email: 'manager@northpole.com',
    phone: '+1-555-9012',
    address: 'Workshop HQ, North Pole',
  },
  {
    _type: 'person',
    name: 'Santa’s Assistant',
    email: 'assistant@northpole.com',
    phone: '+1-555-3456',
    address: "Santa's Office, North Pole",
  },
  {
    _type: 'person',
    name: 'Christmas Eve Coordinator',
    email: 'eve.coordinator@northpole.com',
    phone: '+1-555-7890',
    address: 'Logistics Center, North Pole',
  },
  {
    _type: 'person',
    name: 'North Pole Chef',
    email: 'chef@northpole.com',
    phone: '+1-555-2345',
    address: 'North Pole Kitchen, North Pole',
  },
  {
    _type: 'person',
    name: 'Santa’s Tailor',
    email: 'tailor@northpole.com',
    phone: '+1-555-6789',
    address: 'Tailor Shop, North Pole',
  },
  {
    _type: 'person',
    name: 'Reindeer Caretaker',
    email: 'caretaker@northpole.com',
    phone: '+1-555-5432',
    address: 'Reindeer Barn, North Pole',
  },
  {
    _type: 'person',
    name: 'North Pole Security Chief',
    email: 'security.chief@northpole.com',
    phone: '+1-555-8765',
    address: 'Security Office, North Pole',
  },
  {
    _type: 'person',
    name: 'Head Elf Counselor',
    email: 'counselor@northpole.com',
    phone: '+1-555-4321',
    address: 'Elf Counseling Office, North Pole',
  },
].map((p) => ({...p, _id: slugify(`person-${p.name}`)}))

export const REINDEER_TYPE_DOCUMENTS = [
  {
    _type: 'reindeer',
    name: 'Dasher',
    shinyNose: false,
    age: 5,
    trainingStatus: 'trained',
    currentHealth: 'healthy',
  },
  {
    _type: 'reindeer',
    name: 'Dancer',
    shinyNose: false,
    age: 4,
    trainingStatus: 'trained',
    currentHealth: 'healthy',
  },
  {
    _type: 'reindeer',
    name: 'Prancer',
    shinyNose: false,
    age: 6,
    trainingStatus: 'trained',
    currentHealth: 'healthy',
  },
  {
    _type: 'reindeer',
    name: 'Vixen',
    shinyNose: false,
    age: 7,
    trainingStatus: 'trained',
    currentHealth: 'healthy',
  },
  {
    _type: 'reindeer',
    name: 'Comet',
    shinyNose: false,
    age: 5,
    trainingStatus: 'trained',
    currentHealth: 'healthy',
  },
  {
    _type: 'reindeer',
    name: 'Cupid',
    shinyNose: false,
    age: 4,
    trainingStatus: 'trained',
    currentHealth: 'healthy',
  },
  {
    _type: 'reindeer',
    name: 'Donner',
    shinyNose: false,
    age: 6,
    trainingStatus: 'trained',
    currentHealth: 'healthy',
  },
  {
    _type: 'reindeer',
    name: 'Blitzen',
    shinyNose: false,
    age: 7,
    trainingStatus: 'trained',
    currentHealth: 'healthy',
  },
  {
    _type: 'reindeer',
    name: 'Rudolph',
    shinyNose: true,
    age: 3,
    trainingStatus: 'trained',
    currentHealth: 'healthy',
  },
  {
    _type: 'reindeer',
    name: 'Olive',
    shinyNose: false,
    age: 4,
    trainingStatus: 'trained',
    currentHealth: 'healthy',
  },
  {
    _type: 'reindeer',
    name: 'Clarice',
    shinyNose: false,
    age: 3,
    trainingStatus: 'untrained',
    currentHealth: 'healthy',
  },
  {
    _type: 'reindeer',
    name: 'Fireball',
    shinyNose: false,
    age: 2,
    trainingStatus: 'untrained',
    currentHealth: 'sick',
  },
].map((r) => ({
  ...r,
  _id: slugify(`reindeer-${r.name}`),
  handler: {
    _type: 'reference',
    _ref: ELF_TYPE_DOCUMENTS[Math.floor(Math.random() * ELF_TYPE_DOCUMENTS.length)]._id,
  },
}))

const SLEIGH_TYPE_DOCUMENTS = [
  {
    _type: 'sleigh',
    name: 'Comet Runner',
    model: 'SR-200',
    mileage: 15000,
    maintenanceHistory: [
      {
        date: '2024-01-10T09:00:00Z',
        description: 'Replaced sleigh runners and re-polished frame.',
      },
      {
        date: '2024-05-15T14:00:00Z',
        description: 'Added extra storage compartments and repainted.',
      },
    ],
  },
  {
    _type: 'sleigh',
    name: 'Blitzen Cruiser',
    model: 'BC-100',
    mileage: 22000,
    maintenanceHistory: [
      {
        date: '2023-12-01T11:00:00Z',
        description: 'Performed full checkup before Christmas Eve.',
      },
    ],
  },
  {
    _type: 'sleigh',
    name: 'Dasher Speeder',
    model: 'DS-300',
    mileage: 18000,
    maintenanceHistory: [
      {
        date: '2024-02-20T10:30:00Z',
        description: 'Repaired steering system and upgraded brakes.',
      },
    ],
  },
  {
    _type: 'sleigh',
    name: 'Vixen Glider',
    model: 'VG-150',
    mileage: 13000,
    maintenanceHistory: [
      {
        date: '2023-11-18T12:00:00Z',
        description: 'Upgraded aerodynamic design for better wind resistance.',
      },
      {
        date: '2024-06-12T09:00:00Z',
        description: 'Replaced harness and seatbelts for extra safety.',
      },
    ],
  },
  {
    _type: 'sleigh',
    name: 'Prancer Skater',
    model: 'PS-400',
    mileage: 25000,
    maintenanceHistory: [
      {
        date: '2024-07-05T15:00:00Z',
        description: 'Added new lighting system and repaired side panels.',
      },
    ],
  },
  {
    _type: 'sleigh',
    name: 'Rudolph Express',
    model: 'RX-500',
    mileage: 27000,
    maintenanceHistory: [
      {
        date: '2024-03-12T13:00:00Z',
        description: 'Replaced headlights and upgraded seating for comfort.',
      },
    ],
  },
  {
    _type: 'sleigh',
    name: 'Cupid Flyer',
    model: 'CF-250',
    mileage: 14000,
    maintenanceHistory: [
      {
        date: '2024-04-10T08:00:00Z',
        description: 'Adjusted runners for smoother landing.',
      },
    ],
  },
  {
    _type: 'sleigh',
    name: 'Donner Voyager',
    model: 'DV-350',
    mileage: 20000,
    maintenanceHistory: [
      {
        date: '2024-05-20T10:00:00Z',
        description: 'Added extra storage and cleaned sleigh interior.',
      },
    ],
  },
  {
    _type: 'sleigh',
    name: 'Olive Skimmer',
    model: 'OS-300',
    mileage: 16000,
    maintenanceHistory: [
      {
        date: '2023-12-22T16:00:00Z',
        description: 'Full maintenance check before Christmas flight.',
      },
    ],
  },
  {
    _type: 'sleigh',
    name: 'Clarice Glider',
    model: 'CG-200',
    mileage: 10000,
    maintenanceHistory: [
      {
        date: '2024-08-02T11:30:00Z',
        description: 'Polished sleigh exterior and replaced footrests.',
      },
    ],
  },
].map((s) => ({...s, _id: slugify(`sleigh-${s.name}`)}))

const WAREHOUSE_TYPE_DOCUMENTS = [
  {
    _type: 'warehouse',
    locationName: 'North Pole Central Storage',
    address: '1 Snowflake Avenue, North Pole',
    capacity: 50000,
  },
  {
    _type: 'warehouse',
    locationName: 'Toyland Distribution Center',
    address: '23 Candy Cane Lane, North Pole',
    capacity: 30000,
  },
  {
    _type: 'warehouse',
    locationName: 'Gift Wrap Warehouse',
    address: '45 Ribbon Road, North Pole',
    capacity: 25000,
  },
  {
    _type: 'warehouse',
    locationName: 'Sleigh Loading Dock',
    address: '101 Reindeer Run, North Pole',
    capacity: 40000,
  },
  {
    _type: 'warehouse',
    locationName: 'Workshop Storage Facility',
    address: '12 Elf Alley, North Pole',
    capacity: 20000,
  },
  {
    _type: 'warehouse',
    locationName: 'Material Reserve Depot',
    address: '56 Timber Way, North Pole',
    capacity: 45000,
  },
  {
    _type: 'warehouse',
    locationName: "Santa's Secret Stash",
    address: '78 Claus Court, North Pole',
    capacity: 15000,
  },
  {
    _type: 'warehouse',
    locationName: 'Toy Prototype Storage',
    address: '9 Invention Lane, North Pole',
    capacity: 22000,
  },
  {
    _type: 'warehouse',
    locationName: 'Overflow Storage',
    address: '88 Stocking Street, North Pole',
    capacity: 35000,
  },
  {
    _type: 'warehouse',
    locationName: 'North Pole Packaging Warehouse',
    address: '3 Gift Wrap Lane, North Pole',
    capacity: 28000,
  },
].map((w) => ({...w, _id: slugify(`warehouse-${w.locationName}`)}))

const TOY_TYPE_DOCUMENTS = [
  {
    _type: 'toy',
    name: 'Building Blocks',
    description: 'A set of colorful building blocks to enhance creativity.',
    quantity: 150,
    manufactureDate: '2024-09-15T09:00:00Z',
  },
  {
    _type: 'toy',
    name: 'Teddy Bear',
    description: 'A soft and cuddly teddy bear with a red bow tie.',
    quantity: 100,
    manufactureDate: '2024-08-12T10:00:00Z',
  },
  {
    _type: 'toy',
    name: 'Toy Train Set',
    description: 'A wooden train set with tracks and stations.',
    quantity: 50,
    manufactureDate: '2024-07-20T11:30:00Z',
  },
  {
    _type: 'toy',
    name: 'Doll House',
    description: 'A multi-story doll house with furniture and accessories.',
    quantity: 30,
    manufactureDate: '2024-06-18T14:00:00Z',
  },
  {
    _type: 'toy',
    name: 'Action Figure',
    description: 'An action figure with multiple points of articulation.',
    quantity: 200,
    manufactureDate: '2024-09-05T08:00:00Z',
  },
  {
    _type: 'toy',
    name: 'Puzzle',
    description: 'A 1000-piece puzzle of a beautiful winter landscape.',
    quantity: 80,
    manufactureDate: '2024-07-30T12:00:00Z',
  },
  {
    _type: 'toy',
    name: 'Remote Control Car',
    description: 'A fast and durable remote control car with rechargeable batteries.',
    quantity: 60,
    manufactureDate: '2024-08-25T09:30:00Z',
  },
  {
    _type: 'toy',
    name: 'Bicycle',
    description: "A children's bicycle with training wheels and a basket.",
    quantity: 40,
    manufactureDate: '2024-05-22T13:00:00Z',
  },
  {
    _type: 'toy',
    name: 'Stuffed Unicorn',
    description: 'A fluffy unicorn plush toy with a rainbow mane.',
    quantity: 120,
    manufactureDate: '2024-09-01T10:15:00Z',
  },
  {
    _type: 'toy',
    name: 'Play-Doh Set',
    description: 'A creative set of Play-Doh with various molds and tools.',
    quantity: 90,
    manufactureDate: '2024-06-10T14:30:00Z',
  },
  {
    _type: 'toy',
    name: 'Robot Kit',
    description: 'A DIY robot building kit with remote control features.',
    quantity: 70,
    manufactureDate: '2024-09-12T08:45:00Z',
  },
  {
    _type: 'toy',
    name: 'Magic Set',
    description: 'A complete magic trick set for young magicians.',
    quantity: 40,
    manufactureDate: '2024-08-28T09:00:00Z',
  },
  {
    _type: 'toy',
    name: 'Race Car Track',
    description: 'A fast-paced race track with two electric cars.',
    quantity: 55,
    manufactureDate: '2024-07-15T10:30:00Z',
  },
  {
    _type: 'toy',
    name: 'LEGO Spaceship',
    description: 'A large LEGO set to build a detailed spaceship.',
    quantity: 100,
    manufactureDate: '2024-08-05T12:00:00Z',
  },
  {
    _type: 'toy',
    name: 'Board Game',
    description: 'A strategic board game for family fun.',
    quantity: 200,
    manufactureDate: '2024-09-10T11:00:00Z',
  },
  {
    _type: 'toy',
    name: 'Toy Drum Set',
    description: 'A colorful drum set for young music enthusiasts.',
    quantity: 30,
    manufactureDate: '2024-06-22T13:45:00Z',
  },
  {
    _type: 'toy',
    name: 'Flying Drone',
    description: 'A small drone with a camera and easy controls.',
    quantity: 45,
    manufactureDate: '2024-08-14T08:00:00Z',
  },
  {
    _type: 'toy',
    name: 'Basketball Hoop',
    description: 'An adjustable basketball hoop for kids.',
    quantity: 25,
    manufactureDate: '2024-05-30T10:15:00Z',
  },
  {
    _type: 'toy',
    name: 'Electric Guitar',
    description: 'A kid-friendly electric guitar with a built-in amplifier.',
    quantity: 35,
    manufactureDate: '2024-07-19T11:30:00Z',
  },
  {
    _type: 'toy',
    name: 'Toy Soldier Set',
    description: 'A set of toy soldiers with various accessories.',
    quantity: 150,
    manufactureDate: '2024-09-07T12:00:00Z',
  },
  {
    _type: 'toy',
    name: 'Toy Kitchen Set',
    description: 'A fully equipped toy kitchen set with utensils and pretend food.',
    quantity: 50,
    manufactureDate: '2024-08-02T14:00:00Z',
  },
  {
    _type: 'toy',
    name: 'Superhero Costume',
    description: 'A superhero costume complete with cape and mask.',
    quantity: 75,
    manufactureDate: '2024-09-05T09:30:00Z',
  },
  {
    _type: 'toy',
    name: 'Toy Airplane',
    description: 'A remote control airplane with high-speed features.',
    quantity: 40,
    manufactureDate: '2024-08-18T13:00:00Z',
  },
  {
    _type: 'toy',
    name: 'Toy Tool Set',
    description: 'A complete tool set for pretend play construction.',
    quantity: 85,
    manufactureDate: '2024-07-25T10:45:00Z',
  },
  {
    _type: 'toy',
    name: 'Rocking Horse',
    description: 'A wooden rocking horse with a soft saddle.',
    quantity: 20,
    manufactureDate: '2024-06-12T09:00:00Z',
  },
  {
    _type: 'toy',
    name: 'Toy Cash Register',
    description: 'A toy cash register with play money and a scanner.',
    quantity: 95,
    manufactureDate: '2024-08-10T11:00:00Z',
  },
  {
    _type: 'toy',
    name: 'Pirate Ship',
    description: 'A detailed pirate ship with action figures and cannons.',
    quantity: 60,
    manufactureDate: '2024-07-30T13:30:00Z',
  },
  {
    _type: 'toy',
    name: 'Stuffed Dinosaur',
    description: 'A large stuffed dinosaur with a friendly face.',
    quantity: 130,
    manufactureDate: '2024-09-03T10:00:00Z',
  },
  {
    _type: 'toy',
    name: 'Water Gun',
    description: 'A high-pressure water gun for summer fun.',
    quantity: 110,
    manufactureDate: '2024-06-28T14:45:00Z',
  },
  {
    _type: 'toy',
    name: 'Bubble Maker',
    description: 'An automatic bubble maker with a large bubble output.',
    quantity: 150,
    manufactureDate: '2024-07-15T09:15:00Z',
  },
].map((t) => ({
  ...t,
  _id: slugify(`toy-${t.name}`),
  storageLocation: {
    _type: 'reference',
    _ref: WAREHOUSE_TYPE_DOCUMENTS[Math.floor(Math.random() * WAREHOUSE_TYPE_DOCUMENTS.length)]._id,
  },
}))

const SUPPLIER_TYPE_DOCUMENTS = [
  {
    _type: 'supplier',
    name: 'Polar Timber Co.',
    email: 'contact@polartimber.com',
    phone: '+1-555-1234',
    address: '102 Lumber Yard Rd, Fairbanks, AK',
  },
  {
    _type: 'supplier',
    name: 'Arctic Plastics Inc.',
    email: 'sales@arcticplastics.com',
    phone: '+1-555-5678',
    address: '200 Frostbite Ave, Anchorage, AK',
  },
  {
    _type: 'supplier',
    name: 'Northern Steel Supplies',
    email: 'support@northernsteel.com',
    phone: '+1-555-9012',
    address: '56 Metalworks Blvd, Nome, AK',
  },
  {
    _type: 'supplier',
    name: 'Frosty Fabrics Ltd.',
    email: 'info@frostyfabrics.com',
    phone: '+1-555-3456',
    address: '78 Stitching Ln, Juneau, AK',
  },
  {
    _type: 'supplier',
    name: 'Snowy Paints & Coatings',
    email: 'orders@snowypaints.com',
    phone: '+1-555-7890',
    address: '12 Colors Dr, Barrow, AK',
  },
  {
    _type: 'supplier',
    name: 'Aurora Glassworks',
    email: 'glass@auroraglassworks.com',
    phone: '+1-555-2345',
    address: '9 Reflection Ct, Anchorage, AK',
  },
  {
    _type: 'supplier',
    name: 'Icicle Rubber Inc.',
    email: 'contact@iciclerubber.com',
    phone: '+1-555-6789',
    address: '77 Tundra Rd, Fairbanks, AK',
  },
  {
    _type: 'supplier',
    name: 'Frozen Textiles Ltd.',
    email: 'support@frozentextiles.com',
    phone: '+1-555-5432',
    address: '32 Fabric Loop, Nome, AK',
  },
  {
    _type: 'supplier',
    name: 'Alaska Timberworks',
    email: 'sales@timberworksak.com',
    phone: '+1-555-8765',
    address: '101 Forest Path, Juneau, AK',
  },
  {
    _type: 'supplier',
    name: 'Glacial Metals Corp.',
    email: 'contact@glacialmetals.com',
    phone: '+1-555-4321',
    address: '22 Alloy St, Barrow, AK',
  },
].map((s) => ({
  ...s,
  _id: slugify(`supplier-${s.name}`),
}))

const MATERIAL_TYPE_DOCUMENTS = [
  {
    _type: 'material',
    name: 'Wood',
    quantity: 1500,
    reorderThreshold: 500,
  },
  {
    _type: 'material',
    name: 'Plastic',
    quantity: 2500,
    reorderThreshold: 1000,
  },
  {
    _type: 'material',
    name: 'Metal Screws',
    quantity: 10000,
    reorderThreshold: 2000,
  },
  {
    _type: 'material',
    name: 'Paint',
    quantity: 300,
    reorderThreshold: 100,
  },
  {
    _type: 'material',
    name: 'Fabric',
    quantity: 500,
    reorderThreshold: 200,
  },
  {
    _type: 'material',
    name: 'Cotton',
    quantity: 800,
    reorderThreshold: 300,
  },
  {
    _type: 'material',
    name: 'Rubber',
    quantity: 1200,
    reorderThreshold: 500,
  },
  {
    _type: 'material',
    name: 'Wool',
    quantity: 400,
    reorderThreshold: 150,
  },
  {
    _type: 'material',
    name: 'Yarn',
    quantity: 700,
    reorderThreshold: 250,
  },
  {
    _type: 'material',
    name: 'Glue',
    quantity: 600,
    reorderThreshold: 200,
  },
  {
    _type: 'material',
    name: 'Cardboard',
    quantity: 2000,
    reorderThreshold: 1000,
  },
  {
    _type: 'material',
    name: 'Glass',
    quantity: 300,
    reorderThreshold: 100,
  },
  {
    _type: 'material',
    name: 'Steel Rods',
    quantity: 150,
    reorderThreshold: 50,
  },
  {
    _type: 'material',
    name: 'Nails',
    quantity: 8000,
    reorderThreshold: 3000,
  },
  {
    _type: 'material',
    name: 'Silk',
    quantity: 350,
    reorderThreshold: 100,
  },
  {
    _type: 'material',
    name: 'Leather',
    quantity: 400,
    reorderThreshold: 150,
  },
  {
    _type: 'material',
    name: 'Velcro',
    quantity: 500,
    reorderThreshold: 200,
  },
  {
    _type: 'material',
    name: 'Foam',
    quantity: 1200,
    reorderThreshold: 500,
  },
  {
    _type: 'material',
    name: 'Thread',
    quantity: 1500,
    reorderThreshold: 500,
  },
  {
    _type: 'material',
    name: 'Copper Wire',
    quantity: 600,
    reorderThreshold: 200,
  },
  {
    _type: 'material',
    name: 'Aluminum Sheets',
    quantity: 400,
    reorderThreshold: 100,
  },
  {
    _type: 'material',
    name: 'Clay',
    quantity: 300,
    reorderThreshold: 100,
  },
  {
    _type: 'material',
    name: 'Brass Fittings',
    quantity: 200,
    reorderThreshold: 50,
  },
  {
    _type: 'material',
    name: 'Rubber Bands',
    quantity: 5000,
    reorderThreshold: 1000,
  },
  {
    _type: 'material',
    name: 'Buttons',
    quantity: 2500,
    reorderThreshold: 1000,
  },
  {
    _type: 'material',
    name: 'Ribbons',
    quantity: 1800,
    reorderThreshold: 500,
  },
  {
    _type: 'material',
    name: 'Feathers',
    quantity: 900,
    reorderThreshold: 300,
  },
  {
    _type: 'material',
    name: 'Plastic Pellets',
    quantity: 4000,
    reorderThreshold: 1000,
  },
  {
    _type: 'material',
    name: 'Sandpaper',
    quantity: 600,
    reorderThreshold: 200,
  },
  {
    _type: 'material',
    name: 'Polystyrene',
    quantity: 1000,
    reorderThreshold: 500,
  },
  {
    _type: 'material',
    name: 'Silicone',
    quantity: 700,
    reorderThreshold: 300,
  },
  {
    _type: 'material',
    name: 'Springs',
    quantity: 1500,
    reorderThreshold: 500,
  },
  {
    _type: 'material',
    name: 'Velvet',
    quantity: 400,
    reorderThreshold: 150,
  },
  {
    _type: 'material',
    name: 'Fur',
    quantity: 300,
    reorderThreshold: 100,
  },
  {
    _type: 'material',
    name: 'Polyester',
    quantity: 500,
    reorderThreshold: 200,
  },
  {
    _type: 'material',
    name: 'Epoxy Resin',
    quantity: 350,
    reorderThreshold: 100,
  },
  {
    _type: 'material',
    name: 'Bamboo',
    quantity: 800,
    reorderThreshold: 300,
  },
  {
    _type: 'material',
    name: 'Ceramic',
    quantity: 500,
    reorderThreshold: 200,
  },
  {
    _type: 'material',
    name: 'Glass Beads',
    quantity: 1000,
    reorderThreshold: 500,
  },
  {
    _type: 'material',
    name: 'Magnets',
    quantity: 200,
    reorderThreshold: 100,
  },
].map((m) => ({
  ...m,
  _id: slugify(`material-${m.name}`),
  supplier: {
    _type: 'reference',
    _ref: SUPPLIER_TYPE_DOCUMENTS[Math.floor(Math.random() * SUPPLIER_TYPE_DOCUMENTS.length)]._id,
  },
}))

export const ALL_TYPE_DOCUMENTS: SanityDocumentLike[] = [
  ...CHILD_TYPE_DOCUMENTS,
  ...EVENT_TYPE_DOCUMENTS,
  ...ELF_TYPE_DOCUMENTS,
  ...GIFT_TYPE_DOCUMENTS,
  ...MATERIAL_TYPE_DOCUMENTS,
  ...PARENT_TYPE_DOCUMENTS,
  ...PEOPLE_TYPE_DOCUMENTS,
  ...REINDEER_TYPE_DOCUMENTS,
  ...SLEIGH_TYPE_DOCUMENTS,
  ...WAREHOUSE_TYPE_DOCUMENTS,
  ...TOY_TYPE_DOCUMENTS,
  ...SUPPLIER_TYPE_DOCUMENTS,
]

const client = getCliClient()

async function run() {
  // Get all unique types
  const uniqueTypes = new Set(ALL_TYPE_DOCUMENTS.map((doc) => doc._type))

  // Delete all existing content
  await client.delete({query: '*[_type in $types]', params: {types: Array.from(uniqueTypes)}})

  // Create new docs
  const tx = client.transaction()
  ALL_TYPE_DOCUMENTS.forEach((doc) => {
    tx.createOrReplace(doc)
  })
  tx.commit({
    autoGenerateArrayKeys: true,
  })
    .then((res) => {
      console.log(res)
    })
    .catch((err) => {
      console.error(err)
    })
}

run()
